<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <Title>Dinja</Title>
        <Authors>akbarishahpar</Authors>
        <Description>DotNet Depenedency Injection Ninja!</Description>
        <PackageProjectUrl>https://github.com/akbarishahpar/Dinja</PackageProjectUrl>
        <RepositoryUrl>https://github.com/akbarishahpar/Dinja</RepositoryUrl>
        <PackageTags>Dependency Injection IoC Dinja</PackageTags>
        <PackageLicenseFile>LICENCE.md</PackageLicenseFile>
        <PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
        <PackageIcon>nuget-icon.png</PackageIcon>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageVersion>1.0.3</PackageVersion>
        <FileVersion>1.0.3</FileVersion>
        <AssemblyVersion>1.0.3</AssemblyVersion>
    </PropertyGroup>

    <ItemGroup>
      <None Include="..\LICENCE.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="..\nuget-icon.png">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
      <None Include="..\README.md">
        <Pack>True</Pack>
        <PackagePath>\</PackagePath>
      </None>
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Configuration" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.4" />
      <PackageReference Include="Microsoft.Extensions.Hosting" Version="9.0.4" />
    </ItemGroup>

</Project>
